id: IF54F71B3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T09:12:00+00:00'
last_modified: '2022-06-08T05:14:22.221092+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W6472
  title: ཆོས་བཤད་གཞན་ཕན་ཟླ་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0296:
      image_group_id: I1KG17043
      title: Volume 1 of chos bshad gzhan phan zla ba/
      total_pages: 327
      order: 1
      base_file: 0296.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
